# UI
osd-font='TsukuARdGothic Std Medium'
osd-level=0
osc=no
title-bar=no
hr-seek=yes
hr-seek-framedrop=yes
watch-later-options-remove=sub-pos

# Cache
cache=yes
cache-secs=600               # network prefetch target (limited by cache-size)
demuxer-max-bytes=1GiB       # demuxer cache limit
demuxer-max-back-bytes=1GiB  # keep played data for seeking back

# Subtitle
sub-font='TsukuARdGothic Std Medium'
sub-pos=90
sub-ass-override=force
sub-color='#D6D6D6'
sub-shadow-offset=0.5
sub-shadow-color='#000000'
sub-gauss=0.7
sub-hinting=normal
sub-ass-force-margins=yes
blend-subtitles=yes

# Audio
audio-channels=7.1,5.1,stereo

# Graphics API
vo=gpu-next
hwdec=auto-safe
fbo-format=rgba16hf

# Color Management: Disable
icc-profile=""
icc-profile-auto=no

# Video Processing 3. Tone Mapping
tone-mapping=spline
target-peak=auto
target-prim=auto
target-trc=auto
target-contrast=auto
hdr-compute-peak=yes
hdr-peak-percentile=99.995   
hdr-peak-decay-rate=20
gamut-mapping-mode=perceptual

# Video Processing 4. Dithering
video-output-levels=full
dither=fruit
dither-depth=auto
dither-size-fruit=8
temporal-dither=no

# Video Processing 2. Scaling
# catmull_rom mitchell hermite
cscale=hermite
glsl-shaders-append="~~/models/shaders/KrigBilateral.glsl"
scale=catmull_rom
glsl-shaders-append="~~/models/shaders/ravu-zoom-ar-r3.hook"
dscale=mitchell
glsl-shaders-append="~~/models/shaders/SSimDownscaler.glsl"
# glsl-shaders-append="~~/models/shaders/ArtCNN_C4F32_DS.glsl"

# Video Processing 1. Debanding
deband=no

# [Low-Bitrate -> Deband]
# profile-cond=video_bitrate < 40000000
# deband=yes
# deband-iterations=4
# deband-threshold=48
# deband-range=16
# deband-grain=48

# [Low-Resolution -> Nvidia-VSR]
# profile-cond=width < 3840 or height < 2160
# vo=gpu-next
# gpu-api=d3d11
# hwdec=d3d11va
# vf=d3d11vpp=scale=2:scaling-mode=nvidia

