# --------------------- UI ---------------------
osd-font='TsukuARdGothic Std Medium'
osd-level=0
osc=no
title-bar=no
hr-seek=yes
hr-seek-framedrop=yes

# ————————---------—— Cache ———————-—---------——
cache=yes
cache-secs=600               # network prefetch target (limited by cache-size)
demuxer-max-bytes=1GiB       # demuxer cache limit
demuxer-max-back-bytes=1GiB  # keep played data for seeking back

# ———————————— Subtitle Settings ———————————————
sub-font='TsukuARdGothic Std Medium'
sub-ass-override=force
sub-color='#D6D6D6'
sub-shadow-offset=0.5
sub-shadow-color='#000000'
sub-gauss=0.7
sub-ass-force-margins=yes
blend-subtitles=yes

# —————--——-————— Audio Settings ————————--—-———
audio-channels=7.1,5.1,stereo
af=lavfi=[loudnorm=I=-16:TP=-1.5:LRA=11]

# ------------------- V API --------------------
vo=gpu-next
# gpu-api=d3d11
# hwdec=d3d11va-copy
fbo-format=rgba16hf

# ---------- Disable Color Management ----------
icc-profile=""
icc-profile-auto=no

# - Video Processing 3. Tone Mapping -----------
tone-mapping=spline
target-peak=auto
target-prim=auto
target-trc=auto
target-contrast=auto
hdr-compute-peak=yes
hdr-peak-percentile=99.995   
hdr-peak-decay-rate=20
gamut-mapping-mode=perceptual

# - Video Processing 4. Dithering --------------
video-output-levels=full
dither=fruit
dither-depth=auto
dither-size-fruit=8
temporal-dither=no

# - Video Processing 2. Scaling ----------------
# catmull_rom mitchell hermite
cscale=hermite
scale=catmull_rom
glsl-shaders-append="~~/shaders/ravu-zoom-ar-r3-yuv.hook"
dscale=mitchell
glsl-shaders-append="~~/shaders/SSimDownscaler.glsl"
# glsl-shaders-append="~~/shaders/nlmeans_luma.glsl"
# glsl-shaders-append="~~/shaders/ArtCNN_C4F32_DS.glsl"

# - Video Processing 1. Debanding --------------
deband=no
# [Low-Bitrate -> Deband]
# profile-cond=video_bitrate < 40000000
# deband=yes
# deband-iterations=4
# deband-threshold=48
# deband-range=16
# deband-grain=48

# [Low-Resolution -> Nvidia-VSR]
# profile-cond=width < 3840 or height < 2160
# vo=gpu-next
# gpu-api=d3d11
# hwdec=d3d11va
# vf=d3d11vpp=scale=2:scaling-mode=nvidia

