-- modified by mpv_slim: cross_platform_config start
ffmpeg_path=
alass_path=
audio_subsync_tool=alass
altsub_subsync_tool=alass
unload_old_sub=yes
overwrite_old_sub=no
-- modified by mpv_slim: cross_platform_config end
