; mpv_slim_onlinesub configuration
; Register at https://opensubtitles.com to get your free API key
api_key=LCxfGDcYU8uh2dKeFQAZNQYQtAhUU8tS
llm_api_key=sk-6c0ff5f5eb924c0dabc463d6200f4ba1
llm_model=deepseek-chat
llm_base_url=https://api.deepseek.com/v1
languages=zh,yue,en
